name: course_deploy
description: Simple build server for course websites
author: Jen Thakar <jthakar@berkeley.edu>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  crypto: ^2.0.2+1
  http_server: ^0.9.6
  git: ^0.5.1
  github: ^3.0.2
  yaml: ^2.1.13
